debug = true

[[rogs]]
name = "system_evtx"
match = "System.*csv$"
capture = {"time" = 0, "level" = 1, "msg" = 2}

[[rogs]]
name = "app_evtx"
match = "Application.*csv$"
capture = {"time" = 0, "level" = 1, "msg" = 2}

[[rogs]]
name = "app"
match = "app.*log$"
capture = "(?P<level>).*(?P<time>)-(?P<level>) (?P<msg>)"

[out]
path = "./merge"
format = "csv"
fields = ["time","level","msg"]
