name: ci
on: [push, pull_request]
jobs:
  ci:
    name: Continuous Integration
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install rust
      uses: actions-rs/toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        profile: default
        override: true
    - name: Install cargo-make
      uses: actions-rs/cargo@master
      with:
        command: install
        args: --debug cargo-make
    - name: Run CI
      if: matrix.rust != 'nightly'
      uses: actions-rs/cargo@master
      with:
        command: make
        args: ci-flow
    - name: Run CI (Allow Failures)
      if: matrix.rust == 'nightly'
      continue-on-error: true
      uses: actions-rs/cargo@master
      with:
        command: make
        args: ci-flow

