name: ci

on:
  push:
  pull_request:

jobs:
  ci:
    name: Ci
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install cargo-make
      run: cargo install cargo-make
    - name: Build and test
      run: makers test
